# Spring properties
spring:
   application:
      name: wweaver-snippet
   #data:
      #mongodb:
         #uri: mongodb://admin:admin@ds061974.mongolab.com:61974/vnr
         #username: wweaver_app
         #password: wweaver_app
         #database: wweaver
         #host: localhost
         #port: 27017
   # Configure SQL H2 database
   datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:file:./db/h2;MODE=MySQL;IGNORECASE=TRUE

   jpa:
      hibernate:
         ddl-auto: update

# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false

server:
   port: 1111   # HTTP (Tomcat) port