# Spring properties
spring:
  application:
    name: Application
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    username: sa
    password:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:db;MODE=MySQL;IGNORECASE=TRUE
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
  servlet: 
    multipart: 
      max-file-size: 10
      max-request-size: 50
          
logging:
  file: logs/dev_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    br.com.sdvs.builder: INFO
